apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-minio
  namespace: minio-dev
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: minio.backup.training
    http:
      paths:
      - path:
        backend:
          service:
            name: minio-svc
            port:
              number: 9000
        path: /
        pathType: Prefix
  - host: console.backup.training
    http:
      paths:
      - path:
        backend:
          service:
            name: minio-svc
            port:
              number: 9090
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - minio.backup.training
    secretName: cert-minios3
status:
  loadBalancer:
    ingress:
    - ip: IP_NODE
